export enum MentorTipType {
  FIXED = "FIXED",
  EVENT = "EVENT",
  ASSET = "ASSET",
  PORTFOLIO_COMPOSITION = "PORTFOLIO_COMPOSITION",
  EDUCATIONAL_ALERT = "EDUCATIONAL_ALERT",
  CONCEPT_EXPLANATION = "CONCEPT_EXPLANATION",
  HEALTHY_BEHAVIOR = "HEALTHY_BEHAVIOR",
}

export enum MentorTriggerType {
  SESSION_START = "SESSION_START",
  PORTFOLIO_VIEW = "PORTFOLIO_VIEW",
  FINANCIAL_EVENT = "FINANCIAL_EVENT",
  MISSION_EVENT = "MISSION_EVENT",
  GAME_LOOP = "GAME_LOOP",
  ASSET_VIEW = "ASSET_VIEW",
}

export enum MentorTipSeverity {
  INFO = "INFO",
  POSITIVE = "POSITIVE",
  WARNING = "WARNING",
}

export enum MentorEducationalConcept {
  RISK = "RISK",
  LIQUIDITY = "LIQUIDITY",
  FIXED_INCOME = "FIXED_INCOME",
  FII = "FII",
  STOCKS = "STOCKS",
  DIVIDENDS = "DIVIDENDS",
  INTEREST = "INTEREST",
  AVERAGE_PRICE = "AVERAGE_PRICE",
  VOLATILITY = "VOLATILITY",
  DIVERSIFICATION = "DIVERSIFICATION",
  EMERGENCY_RESERVE = "EMERGENCY_RESERVE",
}

export enum MentorGameLoopMoment {
  SESSION_START = "SESSION_START",
  HOME = "HOME",
  PORTFOLIO = "PORTFOLIO",
  AFTER_FINANCIAL_OPERATION = "AFTER_FINANCIAL_OPERATION",
  AFTER_MISSION = "AFTER_MISSION",
  CITY_VIEW = "CITY_VIEW",
}
